---
abstract: 'Associate user-defined magic to variables from Perl.'
author:
  - 'Vincent Pit <perl@profvince.com>'
build_requires:
  Carp: '0'
  Config: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
  XSLoader: '0'
  base: '0'
configure_requires:
  Config: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Variable-Magic
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '0'
  XSLoader: '0'
  base: '0'
  perl: '5.008'
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Name=Variable-Magic
  homepage: http://search.cpan.org/dist/Variable-Magic/
  license: http://dev.perl.org/licenses/
  repository: http://git.profvince.com/?p=perl%2Fmodules%2FVariable-Magic.git
version: '0.55'
